### ISSUE TITLE
Re-number each CAN interface object to be the same on both robots.

### ISSUE THREAD

**Issue by TarkanAl-Kazily** [Spartronics4915/2015-Recycle-Rush#116]
I'll admit it, 'twas a stupid idea.
Set them like so (both in the code and through the CAN web interface)
MOTOR_PORT_LEFT_FRONT = 10
MOTOR_PORT_LEFT_REAR = 11
MOTOR_PORT_RIGHT_FRONT = 12
MOTOR_PORT_RIGHT_REAR = 13
MOTOR_PORT_ELEVATOR_WINCH = 14
PCM_NODE_ID = 0
PDP = 0

**Comment by phroa** [comment]
Addressed in commit 80ec6b9
