### ISSUE TITLE
Debug Logs

### ISSUE THREAD

**Issue by TarkanAl-Kazily** [Spartronics4915/2015-Recycle-Rush#24]
We need a system that we can use to create readable and usable debug messages everywhere in our code. These can be just System.out.println() that we read from the Riolog, or it can be more advanced. For example, a useful feature would be to be able turn off debug messages for certain sections of the code when it no longer needs to be debugged.

**Comment by MichaelaLeung** [comment]
The custom debugger is now operational and can be utilized using the directions found on the wiki under Custom Debugger. This issue can now be closed

**Comment by phroa** [comment]
Info here https://github.com/Spartronics4915/2015-Recycle-Rush/wiki/Custom-Debugger
