### ISSUE TITLE
Complete minimum functionality for mecanum drive train

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2015-Recycle-Rush#34]
Driver has the basic functionality required for steering our 2015 robot. This includes:
- support for omnidirectional movements
- some-level of finer movement controls for precision driving

**Comment by MichaelaLeung** [comment]
We need to 
1. Figure out control mode settings.
2. Add throttle for more precise control

**Comment by MichaelaLeung** [comment]
Also we made a checklist for the Talons with the encoders for autonomous which can be found here: https://github.com/Spartronics4915/2015-Recycle-Rush/wiki/Mecanum-Drive

**Comment by MichaelaLeung** [comment]
We have decided not to use a throttle as the speed will probably remain constant

**Comment by MichaelaLeung** [comment]
The functionality has been implemented and this issue can be closed
