### ISSUE TITLE
Outline and align on autonomous strategy for 2015 robot

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2015-Recycle-Rush#35]
Our autonomous strategy will drive implementation of the autonomous code. Given that:
- Establish a small cross-functional team (programming, marketing, mechanical, electronics, strategy/rules)
- Discuss various approaches, and outline our 2015 autonomous strategy (note: give yourself a set time limit, 30-45mins, to ensure it doesn't drag on)
- Present to the Spartronics team and reach alignment on strategy, and get agreement on requirements to programming and electronics/mechanical
  - Ideally, beginning of Saturday (1/31), we reached an agreement as a team

**Comment by phroa** [comment]
re #28
