### ISSUE TITLE
Drivetrain Testing Goals

### ISSUE THREAD

**Issue by phroa** [Spartronics4915/2015-Recycle-Rush#41]
- [x] Prop up robot, test individual wheel rotation
- [x] Simultaneous wheel rotation (front, back, left, right sides)
- [x] Drive forwards
- [x] Drive backwards
- [x] Strafe left
- [x] Strafe right
- [x] Strafe diagonally
- [x] Rotate in place
- [ ] Rotate while driving
- [x] Drive certain distances

**Comment by TarkanAl-Kazily** [comment]
field control is necessary for rotation while driving.
