### ISSUE TITLE
Add Gyro to robot, and include it in our mecanum drive

### ISSUE THREAD

**Issue by TarkanAl-Kazily** [Spartronics4915/2015-Recycle-Rush#64]
We have a Gyroscope that we can add and use with our mecanumDrive_Cartesian() method call.

**Comment by TarkanAl-Kazily** [comment]
Accomplished through Noah's field drive option.

**Comment by phroa** [comment]
Field drive hasn't been deployed to the robot as far as I can tell.
Revision on the robot is 1f2e5674

**Comment by binnur** [comment]
> Revision on the robot is 1f2e5674

Love it!! :)

--B
