### ISSUE TITLE
Fix 'MoveStraightGivenDistance' command 

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2015-Recycle-Rush#67]
MoveStraightGivenDistance is using 'speed' to measure the distance traveled. Code needs to be changed to use getPosition() (not getEncPosition()) to track distance traveled. From documentation, getPosition() is updated every 20ms, vs getEncPosition() every 100ms. 
- given distance in some measure (inches), convert number of encoder ticks that needs to be observed: note, one rotation of our wheel = 1000 encoder ticks
- drive until desired distance (measured by encoder ticks) is reached. The algorithm could be an average of all 4 wheels, or depending on driving forward/backward, average of the 2 front/backward wheels

**Comment by TarkanAl-Kazily** [comment]
Likely unnecessary now, because we don't use it in more than one old command.
