### ISSUE TITLE
Ensure limit switch for elevator mode is set correctly

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2015-Recycle-Rush#81]
Per Talon SRX user manual, ensure limit switches wired for 'normally open' with neutral brake mode. This will ensure the motor automatically is disabled if a limit switch is triggered. 
1. Limit Switch and Neutral Brake Mode
   4.1. Default Settings
   An “out of the box” Talon will default with the limit switch setting of “Normally Open” for both forward and reverse. This means that motor drive is allowed when a limit switch input is not closed (i.e. not connected to ground). When a limit switch input is closed (is connected to ground) the Talon SRX will disable motor drive and individually blink both LEDs red in the direction of the fault (red blink pattern will move towards the M+/white wire for positive limit fault, and towards M-/green wire for negative limit fault).

**Comment by TarkanAl-Kazily** [comment]
We wan't to be able to control the elevator motor when the limit switches are pressed. We do not want to have it ever automatically disabled.
