### ISSUE TITLE
Add comment for 'DEFAULT_MAX_OUTPUT' in RobotMap.java

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2015-Recycle-Rush#82]
In Speed controller mode, the setMaxOutput is used as a scaling factor. 

// 950 is the change in encoder position in 100ms = ~15ft/sec or ((950_10)/1000_3.14*6/12)
public static final double DEFAULT_MAX_OUTPUT = 950;
driveTrainRobotDrive.setMaxOutput(DEFAULT_MAX_OUTPUT);

**Comment by BenDeVries** [comment]
Added the comment.
