### ISSUE TITLE
Vision to check IF camera is available

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2015-Recycle-Rush#93]
If camera is not available/connected, the vision code in Robot.java is causing exception errors. Please wrap the code to check if camera is connected before executing the vision commands.

**Comment by TarkanAl-Kazily** [comment]
I think this is completed. We will check.

**Comment by gabetrav** [comment]
Yep it is... Dont know how to check it off

**Comment by TarkanAl-Kazily** [comment]
Thanks Gabe
